// This file is generated by Slice Machine. Update with care!

import ArticleContent from './ArticleContent';
import ArticleHeading from './ArticleHeading';

export {
	ArticleContent,
	ArticleHeading,
};

export const components = {
	article_content: ArticleContent,
	article_heading: ArticleHeading,
};
